[package]
name = "rocket-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
diesel = { version="2.0.0-rc.0", features=["postgres"]}
rocket_sync_db_pools = { version="0.1.0-rc.2", default-features = false, features = ["diesel_postgres_pool"] }

